# Generated by Django 4.1.7 on 2023-04-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servesname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=300)),
                ('descrption', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OffersBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=300)),
                ('Message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
