# Generated by Django 4.1.7 on 2023-04-04 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='patients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pATIENT', to='test.patient'),
            preserve_default=False,
        ),
    ]
