# Generated by Django 4.1.7 on 2023-04-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_offers_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='patients',
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.offers'),
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='patients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pATIENT', to='test.patient'),
            preserve_default=False,
        ),
    ]
