# Generated by Django 4.1.7 on 2023-04-05 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_remove_offers_patients_offersbooking_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersbooking',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pATIENT', to='test.patient'),
        ),
    ]
