# Generated by Django 4.1.7 on 2023-04-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_alter_offersbooking_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersbooking',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.offers'),
        ),
    ]
