# Generated by Django 4.1.7 on 2023-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_alter_offersbooking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
