# Generated by Django 4.1.7 on 2023-04-06 02:42

from django.db import migrations, models
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_patient_city_alter_patient_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersbooking',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='offersbooking',
            name='Message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offersbooking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offersbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
