# Generated by Django 4.1.7 on 2023-04-06 14:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_offersbooking_phonenumber_offersbooking_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersbooking',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='offersbooking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offersbooking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
