# Generated by Django 4.1.7 on 2023-04-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_offers_created_at_offersbooking_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='offersbooking',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test.property')),
            ],
            bases=('test.property',),
        ),
        migrations.CreateModel(
            name='Knew',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test.property')),
            ],
            bases=('test.property',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test.property')),
            ],
            bases=('test.property',),
        ),
    ]
