# Generated by Django 4.1.7 on 2023-04-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_property_alter_offers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersbooking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.doctor'),
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='knew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.knew'),
        ),
        migrations.AddField(
            model_name='offersbooking',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.section'),
        ),
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
