# Generated by Django 4.1.7 on 2023-04-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_callcenter_callcentermanager_customer_doctor_and_more'),
        ('test', '0012_offersbooking_date_offersbooking_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersbooking',
            name='Callcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.callcenter'),
        ),
    ]
