# Generated by Django 4.1.7 on 2023-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrier_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYEE', 'employee'), ('MANAGER', 'manager'), ('CUSTOMER', 'customer'), ('CALLCENTER', 'callCenter'), ('MARKETING', 'marketing'), ('DOCTOR', 'doctor'), ('PATIENT', 'patient'), ('CALLCENTERMANAGER', 'callcentermanager')], default='', help_text='This is role user in system', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
